FROM python:3.9
ENV PTYHONBUFFERED 1
WORKDIR /topology
COPY /Topology_discovery/requirements.txt /topology/requirements.txt
#RUN pip install six
#RUN pip install paramiko==2.8.0
RUN pip install -r requirements.txt
