version: '3.8'
services:
  rabbitmq-microservice:
    image: rabbitmq:3.9.10
    restart: always 
    ports:
      - 5672:5672
      - 15672:15672

  topology_discovery:
    build:
      context: .
      dockerfile: Topology_discovery/Dockerfile
    volumes:
      - ./Topology_discovery:/topology
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq-microservice
  
  preprocessing-microservice:
    build:
      context: .
      dockerfile: Preprocessing_microservice/Dockerfile
    volumes:
      - ./Preprocessing_microservice:/preprocessing
    stdin_open: true 
    tty: true
    depends_on: 
      - rabbitmq-microservice
  
  random_generator-microservice:
    build:
      context: .
      dockerfile: Random_generator_microservice/Dockerfile
    volumes:
      - ./Random_generator_microservice:/random_generator
    stdin_open: true 
    tty: true
    depends_on: 
      - rabbitmq-microservice

  ilp:
    build:
      context: .
      dockerfile: ILP/Dockerfile
    volumes:
      - ./ILP:/ILP
    stdin_open: true 
    tty: true
    depends_on: 
      - rabbitmq-microservice

  jetconf:
    build:
      context: .
      dockerfile: Jetconf/Dockerfile
    volumes:
      - ./Jetconf:/Jetconf
    stdin_open: true 
    tty: true
    ports:
      - 8443:8443
      - 80:80
      - 8080:8080
      - "10001-10020:10001-10020"
      - 443:443
    #network_mode: host
    depends_on: 
      - rabbitmq-microservice
   # network_mode: bridge
   # extra_hosts:
    #  - "host.docker.internal:host-gateway"
   # network_mode: "host"
  
  southconf:
    build:
      context: .
      dockerfile: Southconf/Dockerfile
    volumes:
      - ./Southconf:/southconf
    stdin_open: true 
    tty: true
    depends_on: 
      - rabbitmq-microservice

# opendaylight:
#    build:
#      context: .
#      dockerfile: Opendaylight/Dockerfile
#    restart: always 
#    stdin_open: true 
#    tty: true
#    ports:
#      - 6633:6633
#      - 8101:8101
#      - 8181:8181
  
  vlan_configurator:
    build:
      context: .
      dockerfile: Vlan_configurator/Dockerfile
    volumes:
      - ./Vlan_configurator:/vlan_configurator
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq-microservice
