version: '3.8'
services:
  rabbitmq-microservice:
    image: rabbitmq:3.9.10
    restart: always 
    ports:
      - 5672:5672
      - 15672:15672
  preprocessing-microservice:
    build:
      context: .
      dockerfile: Preprocessing_microservice/Dockerfile
    volumes:
      - ./Preprocessing_microservice:/preprocessing
    stdin_open: true 
    tty: true
    depends_on: 
      - rabbitmq-microservice
