version: '3.8'
services:
  rabbitmq-microservice:
    image: rabbitmq:3.9.10
    restart: always 
    ports:
      - 5672:5672
      - 15672:15672
  
  preprocessing-microservice:
    build:
      context: .
      dockerfile: Preprocessing_microservice/Dockerfile
    volumes:
      - ./Preprocessing_microservice:/preprocessing
    stdin_open: true 
    tty: true
    depends_on: 
      - rabbitmq-microservice
  
  random_generator-microservice:
    build:
      context: .
      dockerfile: Random_generator_microservice/Dockerfile
    volumes:
      - ./Random_generator_microservice:/random_generator
    stdin_open: true 
    tty: true
    depends_on: 
      - rabbitmq-microservice

  ilp:
    build:
      context: .
      dockerfile: ILP/Dockerfile
    volumes:
      - ./ILP:/ILP
    stdin_open: true 
    tty: true
    depends_on: 
      - rabbitmq-microservice

  southconf:
    build:
      context: .
      dockerfile: Southconf/Dockerfile
    volumes:
      - ./Southconf:/southconf
    stdin_open: true 
    tty: true
    depends_on: 
      - rabbitmq-microservice

  opendaylight:
    image: gabrielorozco20/odl_tsn:latest
    restart: always 
    stdin_open: true 
    tty: true
    ports:
      - 6633:6633
      - 8101:8101
      - 8181:8181
  
