GLOBAL:
    TIMEZONE: "Europe/Prague"
    LOGFILE: "-"
    PIDFILE: "/tmp/jetconf.pid"
    PERSISTENT_CHANGES: false
    LOG_LEVEL: "debug"
    LOG_DBG_MODULES: ["usr_conf_data_handlers", "nacm", "data"]
    YANG_LIB_DIR: "/home/jukebox-jetconf/yang-modules"
    DATA_JSON_FILE: "/home/jukebox-jetconf/tsn-example.json"
    BACKEND_PACKAGE: "jetconf_jukebox"

HTTP_SERVER:
    DOC_ROOT: "/home/jetconf/data/doc-root"
    DOC_DEFAULT_NAME: "index.html"
    API_ROOT: "/restconf"
    SERVER_NAME: "jetconf-h2"
    SERVER_SSL_CERT: "/home/jetconf/data/server_localhost.crt"
    SERVER_SSL_PRIVKEY: "/home/jetconf/data/server_localhost.key"
    CA_CERT: "/home/jetconf/data/ca.pem"

NACM:
    ENABLED: true
    ALLOWED_USERS: ["example@mail.cz"]
